//import logging

using System.Text;

namespace ArgonautReverse
{
	public delegate (string name, int size, int start) DelDirStructUnpacker(Parser reader);
	public delegate void DelDirStructPacker(BinaryWriter writer, string name, int size, int start);

	public sealed class G
	{
		public string Title{get;}
		public int ReleaseYear{get;}
		public string FilenameDAT{get;}
		public string FilenameDIR{get;}
		public DelDirStructPacker PackDIR{get;}
		public DelDirStructUnpacker UnpackDIR{get;}

		private G(string title,int release_year,string dat_filename = null,string dir_filename = null,DelDirStructPacker dir_struct_pack = null,DelDirStructUnpacker dir_struct_unpack = null)
		{
			this.Title = title;
			this.ReleaseYear = release_year;
			this.FilenameDAT = dat_filename;
			this.FilenameDIR = dir_filename;
			this.PackDIR = dir_struct_pack;
			this.UnpackDIR = dir_struct_unpack;
		}

		private static (string name, int size, int start) _default_struct_unpacker(Parser reader)
		{
			//Little Endian, 12 byte string, followed by two 32-bit integers
			//Struct("<12sII")
			var name = Encoding.ASCII.GetString(reader.ReadBytes(12));
			int size = reader.ReadInt32();
			int start = reader.ReadInt32();
			return (name, size, start);
		}
		private static void _default_struct_packer(BinaryWriter writer, string name, int size, int start)
		{
			//Little Endian, 12 byte string, followed by two 32-bit integers
			//Struct("<12sII")
			writer.Write(Encoding.ASCII.GetBytes(name.PadRight(12, '\0')));
			writer.Write((int)size);
			writer.Write((int)start);
		}


		private static (string name, int size, int start) Croc1_Unpack(Parser reader)
		{
			//Little Endian, 12 byte string, two 32-bit integers, 4 byte padding
			//Struct("<12sII4x")
			var name = Encoding.ASCII.GetString(reader.ReadBytes(12));
			int size = reader.ReadInt32();
			int start = reader.ReadInt32();
			_ = reader.ReadInt32();//Padding
			return (name, size, start);
		}
		private static void Croc1_Pack(BinaryWriter writer, string name, int size, int start)
		{
			//Little Endian, 12 byte string, two 32-bit integers, 4 byte padding
			//Struct("<12sII4x")
			writer.Write(Encoding.ASCII.GetBytes(name.PadRight(12, '\0')));
			writer.Write((int)size);
			writer.Write((int)start);
			writer.Write((int)0);//Padding
		}

		public static readonly G CROC_1_PS1 = new G("Croc 1 PS1", 1997, "CROCFILE.1", "CROCFILE.DIR", Croc1_Pack, Croc1_Unpack);
		public static readonly G CROC_2_PS1 = new G("Croc 2 PS1", 1999, "CROCII.DAT", "CROCII.DIR", _default_struct_packer, _default_struct_unpacker);
		public static readonly G CROC_2_DEMO_PS1 = new G("Croc 2 Demo PS1", 1999, "CROCII.DAT", "CROCII.DIR", _default_struct_packer, _default_struct_unpacker);
		public static readonly G CROC_2_DEMO_PS1_DUMMY = new G("Croc 2 Demo PS1 (Dummy)", 1999, "DUMMY.DAT", null);
		public static readonly G HARRY_POTTER_1_PS1 = new G("Harry Potter 1 PS1", 2001, "POTTER.DAT", "POTTER.DIR", _default_struct_packer, _default_struct_unpacker);
		public static readonly G HARRY_POTTER_2_PS1 = new G("Harry Potter 2 PS1", 2002, "POTTER.DAT", "POTTER.DIR", _default_struct_packer, _default_struct_unpacker);
	}

	public class Configuration
	{
		public G game;
		public bool ignore_warnings;
		public bool debug;
		public Configuration(G game, bool ignore_warnings = false, bool debug = false)
		{
			this.game = game;
			this.ignore_warnings = ignore_warnings;// If False, warnings stop program execution
			//logging.basicConfig(format="%(message)s", level=logging.DEBUG if debug else logging.WARNING)
			this.debug = debug;
		}

		public static readonly G[] SUPPORTED_GAMES = new G[]
		{
			G.CROC_1_PS1,
			G.CROC_2_PS1,
			G.CROC_2_DEMO_PS1,
			G.CROC_2_DEMO_PS1_DUMMY,
			G.HARRY_POTTER_1_PS1,
			G.HARRY_POTTER_2_PS1,
		};
		//Croc 1 parsing is not supported, but it can be sliced
		public static readonly G[] PARSABLE_GAMES = new G[]
		{
			G.CROC_2_PS1,
			G.CROC_2_DEMO_PS1,
			G.CROC_2_DEMO_PS1_DUMMY,
			G.HARRY_POTTER_1_PS1,
			G.HARRY_POTTER_2_PS1,
		};
		public static readonly G[] SLICEABLE_GAMES = SUPPORTED_GAMES;

		public const string wavefront_header = "# Generated by ps1_argonaut reverse tools: https://github.com/OverSurge/PS1-Argonaut-Reverse\n";
		public const string wav_header = "Generated by ps1_argonaut reverse tools: https://github.com/OverSurge/PS1-Argonaut-Reverse";
	}
}